export const data=[
    {
        "id":1,
        "user":"Riya",
        "purchase":100,
        "commission":1000,
        "earnings":100,
        "status":"VERIFIED",
        "date":"2018-07-08"
    },
      {
        "id":2,    
        "user":"Diksha",
        "purchase":200,
        "commission":2000,
        "earnings":50,
        "status":"UNVERIFIED",
        "date":"2018-01-02"
    },
      {
          "id":3,
        "user":"Mona",
        "purchase":300,
        "commission":3000,
        "earnings":200,
        "status":"VERIFIED",
        "date":"2018-03-04"
    },
      {
          "id":4,
        "user":"Priya",
        "purchase":400,
        "commission":4000,
        "earnings":150,
        "status":"UNVERIFIED",
        "date":"2018-05-06"
    }
]